workspace: My Workspace

services:
  - type: web
    name: hit-me-game
    runtime: node
    rootDir: dodgeball/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
